---
language: ruby
rvm:
- 2.3.1
- 2.0.0
- 1.9.3

before_install:
install:
  - bundle install
before_script:
script:
  - rails test
after_success:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script: