---
database:
  image: postgres:9.6.24
  environment:
    POSTGRES_USER: rails
    POSTGRES_PASSWORD: rails_db_pass
  ports:
    - '5432:5432'
  volumes:
    - rails-db:/var/lib/postgresql/data

redis:
  image: redis:7.2.4
  ports:
    - '6379:6379'
  volumes:
    - rails-redis:/var/lib/redis/data

app:
  build: .
  ports:
    - '3000:3000'